databases:
  - name: fbclone
    databaseName: fbclone
    user: fbclone

services:
  - type: web
    name: fbclone
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fbclone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
